import { useState } from 'react'
import data from './../../players_stat.json';
import heroes from './../../data/heroes.json';
import leagues from './../../leagues.json';
import totalCsvUrl from './../../data/group_stage/total.csv?url';
import fantasyScoreCsvUrl from './../../data/group_stage/fantasy_score.csv?url';
import totalCsvRaw from './../../data/group_stage/total.csv?raw';
import seriesStatScoresRaw from './../../data/group_stage/series_stat_scores.csv?raw';
import totalCsvUrlMainEvent from './../../data/main_event/total.csv?url';
import fantasyScoreCsvUrlMainEvent from './../../data/main_event/fantasy_score.csv?url';
import totalCsvRawMainEvent from './../../data/main_event/total.csv?raw';
import { Select } from '@headlessui/react'
import './App.css'

const downloadCsv = async (url, baseName) => {
  const response = await fetch(url);
  const blob = await response.blob();
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${baseName}_${timestamp}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
};

const SummaryLabel = ({ children, description }) => (
  <span className='group relative whitespace-nowrap'>
    <span
      className='cursor-help border-b border-dotted border-white border-opacity-60 focus:outline-none focus:ring-1 focus:ring-yellow-400'
      tabIndex={0}
    >
      {children}
    </span>
    <span
      role='tooltip'
      className='invisible absolute bottom-full left-0 z-20 mb-2 w-max max-w-xs rounded-md bg-gray-900 px-3 py-2 text-xs leading-relaxed text-white shadow-lg opacity-0 transition-opacity group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100'
    >
      {description}
    </span>
  </span>
);

const multipliers = {
  'kills': 107,
  'deaths': 195,
  'creep_score': 3,
  'gpm': 2,
  'madstone_collected': 13,
  'tower_kills': 352,
  'obs_placed': 117,
  'camps_stacked': 234,
  'runes_grabbed': 141,
  'watchers_taken': 147,
  'smokes_used': 293,
  'roshan_kills': 1172,
  'teamfight_participation': 2124,
  'stuns': 10,
  'tormentor_kills': 879,
  'courier_kills': 703,
  'firstblood': 1934
};

const titlesInfo = {
  'crimson': {
    name: 'Crimson',
    description: 'when playing a red hero',
    percent: 6,
  },
  'cerulean': {
    name: 'Cerulean',
    description: 'when playing a blue hero',
    percent: 11,
  },
  'emerald': {
    name: 'Emerald',
    description: 'when playing a green hero',
    percent: 6
  },
  'royal': {
    name: 'Royal',
    description: 'when playing a purple hero',
    percent: 10
  },
  'golden': {
    name: 'Golden',
    description: 'when playing a yellow or brown hero',
    percent: 8
  },
  'elemental': {
    name: 'Elemental',
    description: 'when playing an aquatic, fiery, or icy hero',
    percent: 8
  },
  'otherworld': {
    name: 'Otherworldly',
    description: 'when playing an undead, demon, or spirit hero',
    percent: 7
  },
  'heroic': {
    name: 'Heroic',
    description: 'when playing a caped or masked hero',
    percent: 9
  }
};

const subtitlesInfo = {
  "lost_games": {
    name: 'Underdog',
    description: "in games where the player loses",
    percent: 6
  },
  "clutch": {
    name: 'Clutch',
    description: 'when playing the last possible match of a series',
    percent: 16
  },
  "lucky": {
    name: 'Lucky',
    description: 'if the match time ends with an 8',
    percent: 21
  },
  "total_deaths_from_torm": {
    name: 'Tormented',
    description: 'if any player dies to a tormentor',
    percent: 23
  },
  "firstblood_before_10min": {
    name: 'Patient',
    description: 'if first blood does not happen until after 10 minutes',
    percent: 23
  },
  "firstblood_before_horn": {
    name: 'Flayed Twins Acolyte',
    description: 'if any player gets first blood before the starting horn',
    percent: 9
  },
  "games<25min": {
    name: 'Decisive',
    description: 'in games that last less than 25 minutes',
    percent: 24
  }
};

// --- Per-game / per-series scoring (group stage CSV data) ---
// A player's raw score for one game is paired with their core/support
// teammate (averaged) or used solo for mid, then a series score takes the
// best 2 of up to 3 games (Bo3) and sums them.

const parseCsv = (raw) => {
  const lines = raw.trim().split(/\r?\n/);
  const headers = lines[0].split(',');
  return lines.slice(1).map(line => {
    const values = line.split(',');
    const row = {};
    headers.forEach((header, i) => { row[header] = values[i]; });
    return row;
  });
};

// Pre-computed raw per-stat series scores (no title/subtitle bonus), one row
// per (series, team, position) pair/solo, generated by
// scripts/compute_series_stat_scores.py.
const seriesStatScoreRows = parseCsv(seriesStatScoresRaw);
const STAT_SCORE_COLUMNS = [
  "kills", "deaths", "creep_score", "gpm", "madstone_collected", "tower_kills",
  "obs_placed", "camps_stacked", "runes_grabbed", "watchers_taken", "smokes_used",
  "roshan_kills", "teamfight_participation", "stuns", "courier_kills",
  "tormentor_kills", "firstblood_claimed",
];

const toFiniteNumber = (value) => {
  const numericValue = Number(value);
  return Number.isFinite(numericValue) ? numericValue : 0;
};

// Keep one row per team and role. Each stat takes that team's best score
// across all of its series, so the table is a best-score comparison rather
// than a list of individual series results.
const bestStatScoreRows = Object.values(seriesStatScoreRows.reduce((rowsByTeamPosition, row) => {
  const key = `${row.teamID}|${row.position}`;
  const current = rowsByTeamPosition[key];

  if (!current) {
    rowsByTeamPosition[key] = {
      ...row,
      ...Object.fromEntries(STAT_SCORE_COLUMNS.map(stat => [stat, toFiniteNumber(row[stat])])),
    };
    return rowsByTeamPosition;
  }

  STAT_SCORE_COLUMNS.forEach(stat => {
    const candidate = toFiniteNumber(row[stat]);
    const currentValue = toFiniteNumber(current[stat]);
    if (candidate > currentValue) {
      current[stat] = candidate;
    }
  });

  return rowsByTeamPosition;
}, {}));

// Builds the derived per-tab indexes from one total.csv's raw text:
// - totalRows: parsed rows
// - tormentorMatchIds: matches where any player died to a Tormentor
// - seriesTeamPositionGames: `${seriesID}|${teamID}|${position}` -> { matchID -> [player rows] }
const buildGameIndexes = (raw) => {
  const totalRows = parseCsv(raw);

  const tormentorMatchIds = new Set(
    totalRows.filter(row => Number(row.tormentor_deaths) > 0).map(row => row.matchID)
  );

  const seriesTeamPositionGames = {};
  totalRows.forEach(row => {
    const key = `${row.seriesID}|${row.teamID}|${row.position}`;
    if (!seriesTeamPositionGames[key]) seriesTeamPositionGames[key] = {};
    if (!seriesTeamPositionGames[key][row.matchID]) seriesTeamPositionGames[key][row.matchID] = [];
    seriesTeamPositionGames[key][row.matchID].push(row);
  });

  return { totalRows, tormentorMatchIds, seriesTeamPositionGames };
};

// One set of indexes per tab, built once from their respective total.csv.
const gameIndexesByTab = {
  group_stage: buildGameIndexes(totalCsvRaw),
  main_event: buildGameIndexes(totalCsvRawMainEvent),
};

const suffixAppliesToRow = (subtitleKey, row, tormentorMatchIds) => {
  switch (subtitleKey) {
    case 'lost_games': return Number(row.win) === 0;
    case 'clutch': return Number(row.isLastGame) === 1;
    case 'lucky': return row.gametime.slice(-1) === '8';
    case 'total_deaths_from_torm': return tormentorMatchIds.has(row.matchID);
    case 'firstblood_before_10min': return Number(row.first_blood_time) > 600;
    case 'firstblood_before_horn': return Number(row.first_blood_time) < 0;
    case 'games<25min': return Number(row.gametime) < 1500;
    default: return false;
  }
};

const titleAppliesToRow = (titleKey, row) => Number(row[`is_${titleKey}`]) === 1;

const computePlayerGameScore = (row, statSlots, titleKey, subtitleKey, tormentorMatchIds) => {
  let total = 0;
  statSlots.forEach(({ stat, multiplier }) => {
    if (!stat) return;
    const weight = multipliers[stat] ?? 1;
    const raw = toFiniteNumber(row[stat]);
    total += stat === 'deaths'
      ? (1950 - raw * 195) * multiplier
      : raw * weight * multiplier;
  });

  let bonusPercent = 0;
  if (titleKey && titleAppliesToRow(titleKey, row)) bonusPercent += titlesInfo[titleKey]?.percent || 0;
  if (subtitleKey && suffixAppliesToRow(subtitleKey, row, tormentorMatchIds)) bonusPercent += subtitlesInfo[subtitleKey]?.percent || 0;

  return total + (total / 100) * bonusPercent;
};

// Best 2 of up to 3 game scores for one (series, team, position) group,
// pairing core/support teammates (averaged) or using mid solo.
const computeSeriesRoleScore = (key, statSlots, titleKey, subtitleKey, seriesTeamPositionGames, tormentorMatchIds) => {
  const gamesByMatch = seriesTeamPositionGames[key];
  if (!gamesByMatch) return { score: 0, playerNames: [] };

  const gameScores = Object.values(gamesByMatch).map(playerRows => {
    const perPlayerScores = playerRows.map(row => computePlayerGameScore(row, statSlots, titleKey, subtitleKey, tormentorMatchIds));
    return perPlayerScores.reduce((a, b) => a + b, 0) / perPlayerScores.length;
  });

  gameScores.sort((a, b) => b - a);
  const bestTwo = gameScores.slice(0, 2);
  const score = bestTwo.reduce((a, b) => a + b, 0);

  const anyGamePlayers = Object.values(gamesByMatch)[0];
  const playerNames = anyGamePlayers.map(row => row.playerName);

  return { score, playerNames };
};

function App() {
  const selectedTournaments = Object.keys(leagues);
  const [selectedRole, setSelectedRole] = useState(0);
  const [isHIW, setIsHIW] = useState(false);
  const [activeTab, setActiveTab] = useState('group_stage');
  const [statSortKey, setStatSortKey] = useState(null);
  const [visiblePositions, setVisiblePositions] = useState({ core: true, mid: true, support: true });

  const getAvgStat = (info, color, statKey) => {
  // Берём только выбранные турниры
  const selectedLeaguesData = Object.entries(info)
    .filter(([leagueId]) => selectedTournaments.includes(leagueId));

  let allValues = [];
  selectedLeaguesData.forEach(([_, leagueData]) => {
    const stats = leagueData?.stats?.[color]?.[statKey];
    if (stats) allValues.push(...stats);
  });

  if (allValues.length === 0) return 0;

  const avg = allValues.reduce((sum, el) => sum + el, 0) / allValues.length;

  // Подбираем индексы для мультипликаторов, соответствующие активной вкладке
  const colorIndexes = [];
  let flatIdx = 0;
  Object.keys(activeRolesConfig).forEach(role => {
    activeRolesConfig[role].forEach(slotColor => {
      if (slotColor === color) colorIndexes.push(flatIdx);
      flatIdx++;
    });
  });

  const multiplier = colorIndexes.reduce((acc, idx) => {
    if (activeSelectedOption[idx] === statKey && info.general.pos === Math.floor(idx / activeSlotsPerRole)) {
      return acc * activeSelectedMultiplier[idx];
    }
    return acc;
  }, 1);

  // Специальная формула для deaths
  if (statKey === "deaths") {
    return ((1950 - avg * 195) * multiplier).toFixed(2);
  }

  // Остальные статы
  const factor = {
    kills: 107,
    creep_score: 3,
    gpm: 2,
    madstone_collected: 13,
    tower_kills: 352,
    roshan_kills: 1172,
    teamfight_participation: 2124,
    stuns: 10,
    tormentor_kills: 879,
    courier_kills: 703,
    firstblood: 1934,
    obs_placed: 117,
    camps_stacked: 234,
    runes_grabbed: 141,
    watchers_taken: 147,
    smokes_used: 293,
  };

  return (avg * (factor[statKey] || 1) * multiplier).toFixed(2);
};

const RedStats = ({ info }) => (
  <div className="bg-red-500 bg-opacity-20 py-2 px-4 rounded-lg">
    {["kills","deaths","creep_score","gpm","madstone_collected","tower_kills"].map(stat => (
      <div key={stat} className='flex justify-between gap-4'>
        <span className='capitalize'>{stat.replace("_"," ")}</span>
        <b className='tabular-nums'>{getAvgStat(info,"red",stat)}</b>
      </div>
    ))}
  </div>
);

const BlueStats = ({ info }) => (
  <div className="bg-blue-500 bg-opacity-20 py-2 px-4 rounded-lg">
    {["obs_placed","camps_stacked","runes_grabbed","watchers_taken","smokes_used"].map(stat => (
      <div key={stat} className='flex justify-between gap-4'>
        <span className='capitalize'>{stat.replace("_"," ")}</span>
        <b className='tabular-nums'>{getAvgStat(info,"blue",stat)}</b>
      </div>
    ))}
  </div>
);

const GreenStats = ({ info }) => (
  <div className="bg-green-500 bg-opacity-20 py-2 px-4 rounded-lg">
    {["roshan_kills","teamfight_participation","stuns","tormentor_kills","courier_kills","firstblood"].map(stat => (
      <div key={stat} className='flex justify-between gap-4'>
        <span className='capitalize'>{stat.replace("_"," ")}</span>
        <b className='tabular-nums'>{getAvgStat(info,"green",stat)}</b>
      </div>
    ))}
  </div>
);

const getAvgForSort = (info, statKey) => {
  // Выбираем только турниры пользователя
  const selectedLeaguesData = Object.entries(info)
    .filter(([leagueId]) => selectedTournaments.includes(leagueId));

  let allValues = [];

  selectedLeaguesData.forEach(([_, leagueData]) => {
    // Проверяем все цвета
    ['red', 'blue', 'green'].forEach(color => {
      const arr = leagueData?.stats?.[color]?.[statKey];
      if (arr) allValues.push(...arr);
    });
  });

  if (allValues.length === 0) return 0;

  return allValues.reduce((sum, v) => sum + v, 0) / allValues.length;
};

  const [sortBy, setSortBy] = useState(null);
  const filteredAndSorted = Object.entries(data)
  .filter(([_, info]) => selectedRole === null || info.general.pos === selectedRole)
  .sort(([_, aInfo], [__, bInfo]) => {
    if (!sortBy) return 0;

    const multiplier = sortBy === 'deaths' ? -1 : 1;

    return multiplier * (getAvgForSort(bInfo, sortBy) - getAvgForSort(aInfo, sortBy));
  });
  
  const roles = {
    0: ['red', 'green', 'red'],
    1: ['red', 'blue', 'green'],
    2: ['blue', 'green', 'blue']
  }

  const rolesExtended = {
    0: ['red', 'green', 'red', 'green', 'red'],
    1: ['red', 'blue', 'green', 'red', 'green'],
    2: ['blue', 'green', 'blue', 'green', 'blue']
  }

  const backgrounds = {
    red: "bg-red-500",
    blue: "bg-blue-500",
    green: "bg-green-500",
  };

  const [selectedOption, setSelectedOption] = useState([null, null, null, null, null, null, null, null, null]);
  const [selectedMultiplier, setSelectedMultiplier] = useState([1, 1, 1, 1, 1, 1, 1, 1, 1]);
  const [selectedTitle, setSelectedTitle] = useState('');
  const [selectedSubtitle, setSelectedSubtitle] = useState('');

  const [selectedOptionExtended, setSelectedOptionExtended] = useState([null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]);
  const [selectedMultiplierExtended, setSelectedMultiplierExtended] = useState([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]);

  const activeRolesConfig = activeTab === 'group_stage' ? roles : rolesExtended;
  const activeSlotsPerRole = activeTab === 'group_stage' ? 3 : 5;
  const activeSelectedOption = activeTab === 'group_stage' ? selectedOption : selectedOptionExtended;
  const setActiveSelectedOption = activeTab === 'group_stage' ? setSelectedOption : setSelectedOptionExtended;
  const activeSelectedMultiplier = activeTab === 'group_stage' ? selectedMultiplier : selectedMultiplierExtended;
  const setActiveSelectedMultiplier = activeTab === 'group_stage' ? setSelectedMultiplier : setSelectedMultiplierExtended;
  const { seriesTeamPositionGames: activeSeriesTeamPositionGames, tormentorMatchIds: activeTormentorMatchIds } = gameIndexesByTab[activeTab];

  return (
    <>
      <div className='p-40 pb-10 relative w-full bg-gray-950 min-h-screen flex flex-col gap-12'>
        <div className='flex justify-end gap-4 absolute top-8 right-8'>
          <button
            className='text-white bg-purple-900 hover:bg-purple-800 rounded-md px-4 py-2 text-sm cursor-pointer'
            onClick={() => downloadCsv(totalCsvUrl, 'total_group_stage')}>
            Download total.csv (Group Stage)
          </button>
          <button
            className='text-white bg-purple-900 hover:bg-purple-800 rounded-md px-4 py-2 text-sm cursor-pointer'
            onClick={() => downloadCsv(fantasyScoreCsvUrl, 'fantasy_score_group_stage')}>
            Download fantasy_score.csv (Group Stage)
          </button>
          <button
            className='text-white bg-purple-900 hover:bg-purple-800 rounded-md px-4 py-2 text-sm cursor-pointer'
            onClick={() => downloadCsv(totalCsvUrlMainEvent, 'total_main_event')}>
            Download total.csv (Main Event)
          </button>
          <button
            className='text-white bg-purple-900 hover:bg-purple-800 rounded-md px-4 py-2 text-sm cursor-pointer'
            onClick={() => downloadCsv(fantasyScoreCsvUrlMainEvent, 'fantasy_score_main_event')}>
            Download fantasy_score.csv (Main Event)
          </button>
        </div>
        {isHIW && (
          <div className='backdrop-blur-sm fixed w-screen h-screen left-0 top-0 bg-gray-950 bg-opacity-50 z-10'>
            <div className='absolute left-[50%] -translate-x-[50%] top-[50%] -translate-y-[50%] backdrop-blur-sm rounded-lg border border-zinc-900 bg-zinc-800 bg-opacity-80 z-10 p-8'>
              <button className='absolute right-8 top-8' onClick={() => setIsHIW(false)}>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" className="size-12">
                  <path fill-rule="evenodd" d="M5.47 5.47a.75.75 0 0 1 1.06 0L12 10.94l5.47-5.47a.75.75 0 1 1 1.06 1.06L13.06 12l5.47 5.47a.75.75 0 1 1-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 0 1-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
                </svg>
              </button>
              <p className="text-white leading-relaxed w-max">
                <span className="block mb-2 font-semibold">Calculation formula:</span>
                <span className="block">
                  (sum of all players stats <b>x</b> their multipliers) <b>+</b> <br />
                  (games played with particular subtitle <b>x</b> subtitle percent <b>/</b> all players matches) <b>+</b> <br />
                  (games played with particular title <b>x</b> title percent <b>/</b> all players matches)
                </span>

                <span className="block mt-4 font-semibold">Example:</span>
                <span className="block mt-2">
                  This year we only track <b>TI 2026</b>, so there's no averaging across tournaments &mdash; everything below comes from TI 2026 matches only.
                  <br />
                  <b>Player X</b> played <b>20</b> matches and picked a red hero in <b>5</b> of them. <br />
                  After choosing the <b>Crimson</b> title, you get <b>+6%</b> whenever the player plays a red hero.
                  <br />
                  Title +percent per game: <u>5 × 6 / 20 = 1.5%</u>
                </span>

                <span className="block mt-2">
                  <b>Subtitles calculation:</b> Same formula, but the condition depends on the subtitle. This year's suffixes:
                  <ul className="list-disc list-inside ml-4 mt-1 space-y-1">
                    <li>the Tormented: +23% if any player dies to a Tormentor</li>
                    <li>the Flayed Twins Acolyte: +9% if any player gets first blood before the starting horn</li>
                    <li>the Patient: +23% if first blood does not happen until after 10 minutes</li>
                    <li>the Underdog: +6% in games where the player loses</li>
                    <li>the Decisive: +24% in games that last less than 25 minutes</li>
                    <li>the Clutch: +16% when playing the last possible match of a series</li>
                    <li>the Lucky: +21% if the match time ends with an 8</li>
                  </ul>
                  <br />
                  Say Player X's team lost <b>8</b> of their <b>20</b> matches, and they pick the <b>Underdog</b> subtitle:
                  <br />
                  Subtitle +percent per game: <u>8 × 6 / 20 = 2.4%</u>
                </span>

                <span className="block mt-4 font-semibold">Player stats:</span>
                <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
                  <li>
                    <b>Kills</b> (base <b>107</b>) with multiplier <b>1.5</b>:
                    average kills × multiplier × base = <u>8.4 × 1.5 × 107 = 1348.20</u>
                  </li>
                  <li>
                    <b>Teamfight participation</b> (base <b>2124</b>) with no extra multiplier:
                    average TF participation × 1 × base = <u>0.62 × 1 × 2124 = 1316.88</u>
                  </li>
                  <li>
                    <b>Creep score</b> (base <b>3</b>) with multiplier <b>1.2</b>:
                    average creep score × multiplier × base = <u>420 × 1.2 × 3 = 1512.00</u>
                  </li>
                </ul>

                <span className="block mt-4 font-semibold">Sum of stats:</span>
                <span className="block mt-1"><u>1348.20 + 1316.88 + 1512.00 = 4177.08</u></span>

                <span className="block mt-4 font-semibold">Final result:</span>
                <span className="block mt-1">
                  ((sum of all stats / 100) × title +percent per game) + ((sum of all stats / 100) × subtitle +percent per game) + sum of all stats = <br />
                  <u>((4177.08 / 100) × 1.5) + ((4177.08 / 100) × 2.4) + 4177.08 = 4339.99</u>
                </span>
              </p>
            </div>
          </div>
        )}
        <section className='w-full flex flex-col gap-4 items-center'>
          <h2 className='text-white font-bold text-5xl'>The international 2026 Fantasy</h2>
          <div className='text-white flex w-full justify-between gap-4'>
            {Object.entries(leagues).map(([league, data]) => (
              <div key={data.name} className='bg-gradient-to-b from-transparent from-20% rounded-md to-purple-900 p-4 flex flex-col w-full'>
                <span className='text-lg'>{data.short_name}</span>
                <div className='flex w-full mt-4'>
                  <SummaryLabel description='Number of matches processed and included in the current data.'>
                    Total matches parsed:
                  </SummaryLabel>
                  <div className='w-full h-[1px] bg-white self-end mb-1 bg-opacity-30'></div>
                  <b className='ml-auto'>{data.total_matches_parsed}</b>
                </div>
                <div className='flex w-full'>
                  <SummaryLabel description='+23% if any player dies to a Tormentor.'>
                    the Tormented:
                  </SummaryLabel>
                  <div className='w-full h-[1px] bg-white self-end mb-1 bg-opacity-30'></div>
                  <b className='ml-auto'>{data.total_deaths_from_torm}</b>
                </div>
                <div className='flex w-full'>
                  <SummaryLabel description='+23% if first blood does not happen until after 10 minutes.'>
                    the Patient:
                  </SummaryLabel>
                  <div className='w-full h-[1px] bg-white self-end mb-1 bg-opacity-30'></div>
                  <b className='ml-auto'>{data.firstblood_before_10min}</b>
                </div>
                <div className='flex w-full'>
                  <SummaryLabel description='+9% if any player gets first blood before the starting horn.'>
                    the Flayed Twins Acolyte:
                  </SummaryLabel>
                  <div className='w-full h-[1px] bg-white self-end mb-1 bg-opacity-30'></div>
                  <b className='ml-auto'>{data.firstblood_before_horn}</b>
                </div>
                <div className='flex w-full'>
                  <SummaryLabel description='+24% in games that last less than 25 minutes.'>
                    the Decisive:
                  </SummaryLabel>
                  <div className='w-full h-[1px] bg-white self-end mb-1 bg-opacity-30'></div>
                  <b className='ml-auto'>{data['games<25min']}</b>
                </div>
              </div>
            ))}
          </div>
        </section>
        <section className='relative w-full flex flex-col gap-4 items-center'>
          <h2 className='text-white font-bold text-5xl'>Select your stats</h2>
          <h3 className='text-white text-center'>Choose your titles, subtitles, stats and their multipliers <br />* Enter fraction instead of percents, for example if you have 270% multiplier enter 2.7 instead.</h3>
          <button className='text-yellow-500 text-2xl absolute right-0 top-12 cursor-pointer' onClick={() => setIsHIW(true)}>How does it counts?</button>
          <div className='flex gap-4'>
            <button
              className={`px-4 py-2 rounded-md cursor-pointer ${activeTab === 'group_stage' ? 'bg-purple-700 text-white' : 'bg-purple-950 text-gray-400'}`}
              onClick={() => setActiveTab('group_stage')}>
              Group Stage
            </button>
            <button
              className={`px-4 py-2 rounded-md cursor-pointer ${activeTab === 'main_event' ? 'bg-purple-700 text-white' : 'bg-purple-950 text-gray-400'}`}
              onClick={() => setActiveTab('main_event')}>
              Main Event
            </button>
          </div>
          <div className='grid w-full max-w-2xl grid-cols-2 gap-4'>
            <Select
              value={selectedTitle}
              onChange={(e) => setSelectedTitle(e.target.value)}
              className='p-2 rounded-sm focus:outline-none'
            >
              <option value="">Select Prefix for all roles</option>
              {Object.keys(data.Xm[19719].titles).map((title, idx) => (
                <option key={`${idx}-${title}`} value={title || ''}>
                  {titlesInfo[title]['name']} {' - +'}{titlesInfo[title]['percent']}{'%'} {titlesInfo[title]['description']}
                </option>
              ))}
            </Select>
            <Select
              value={selectedSubtitle}
              onChange={(e) => setSelectedSubtitle(e.target.value)}
              className='p-2 rounded-sm focus:outline-none'
            >
              <option value="">Select Suffix for all roles</option>
              {Object.entries(subtitlesInfo).map(([name, info], idx) => (
                <option key={`${idx}-${name}`} value={name || ''}>
                  {info.name} {' - +'}{info.percent}{'%'} {info.description}
                </option>
              ))}
              <option disabled className='text-red-600'>
                the Cruel - +13% if a player is killed while in their own fountain (NO DATA)
              </option>
            </Select>
          </div>
          <div className='grid grid-cols-3 gap-4'>
            {Object.keys(activeRolesConfig).map(role => (
              <div
              key={role}
              className='flex flex-col gap-2 p-4 bg-gradient-to-b from-purple-900 rounded-md to-transparent'>
                <div className='flex flex-col gap-4'>
                  <h2 className='text-center text-white text-5xl'>{{0: 'Core', 1: 'Mid', 2: 'Support'}[role]}</h2>
                  <div className='flex flex-col gap-2'>
                  {activeRolesConfig[role].map((color, idx) => (
                    <div
                    key={idx}
                    className={`flex justify-between gap-2 ${backgrounds[color]} bg-opacity-30 rounded-md px-4 py-6`}
                    >
                      <Select
                      value={activeSelectedOption[idx + (role * activeSlotsPerRole)] || ''}
                      onChange={(e) => setActiveSelectedOption(prev => {
                        const updated = [...prev];
                        updated[idx + (role * activeSlotsPerRole)] = e.target.value;
                        return updated;
                      })}
                      className='w-[100%] p-1 rounded-sm'
                      >
                        <option value="">None</option>
                        {Object.keys(data.Xm[19719].stats[color]).map((stat, idx) => (
                          <option key={`${idx}-${stat}`} value={stat || ''} className={stat === 'watchers_taken' ? 'text-red-600' : ''}>
                            {stat.replace('_', ' ')}
                            {stat === 'watchers_taken' ? '(data is not 100% accurate)' : ''}
                          </option>
                        ))}
                        {color == 'blue' ? (
                          <option disabled className='text-red-600'>
                            lotuses grabbed(NO DATA)
                          </option>
                        ) : ''}
                      </Select>
                       <input
                      type="number"
                      className='w-[30%] text-black rounded-sm p-1 focus:outline-none focus:ring-0 [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none [appearance:textfield]'
                      value={activeSelectedMultiplier[idx + (role * activeSlotsPerRole)] || ''}
                      onChange={(e) =>
                        setActiveSelectedMultiplier(prev => {
                          const updated = [...prev];
                          updated[idx + (role * activeSlotsPerRole)] = Number(e.target.value);
                          return updated;
                        })
                      } />
                    </div>
                  ))}
                  </div>
                </div>
                <div className='flex flex-col items-center'>
                  <h6 className="text-white text-3xl my-4">Best players:</h6>
                  <ul className='text-white flex flex-col w-full gap-1'>
                    {(() => {
                      const positionLabel = { 0: 'core', 1: 'mid', 2: 'support' }[role];
                      const statSlots = activeRolesConfig[role].map((_, idx) => ({
                        stat: activeSelectedOption[idx + role * activeSlotsPerRole],
                        multiplier: activeSelectedMultiplier[idx + role * activeSlotsPerRole] || 1,
                      }));
                      const titleKey = selectedTitle;
                      const subtitleKey = selectedSubtitle;

                      const keys = Object.keys(activeSeriesTeamPositionGames).filter(key => key.endsWith(`|${positionLabel}`));

                      const rankedTeams = keys
                        .map(key => {
                          const { score, playerNames } = computeSeriesRoleScore(key, statSlots, titleKey, subtitleKey, activeSeriesTeamPositionGames, activeTormentorMatchIds);
                          const teamName = Object.values(activeSeriesTeamPositionGames[key])[0][0].teamName;
                          return { key, teamName, playerNames, score };
                        })
                        .sort((a, b) => b.score - a.score);

                      const shownTeams = [];
                      const seenTeamNames = new Set();
                      rankedTeams.forEach(team => {
                        if (!seenTeamNames.has(team.teamName)) {
                          seenTeamNames.add(team.teamName);
                          shownTeams.push(team);
                        }
                      });

                      return shownTeams
                        .slice(0, 7)
                        .map(({ key, teamName, playerNames, score }) => (
                          <li key={key} className='whitespace-nowrap flex justify-between'>
                            <span>{teamName} ({playerNames.join(' & ')})</span><div className='h-[1px] w-full bg-white bg-opacity-20 self-end mb-1'></div><span>{score.toFixed(2)}</span>
                          </li>
                        ));
                    })()}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </section>
        <div className='w-full text-gray-300 py-16'>
          <p>* All data was taken using <a href="https://docs.opendota.com/" className='underline text-blue-500' target='_blank' rel="noopener noreferrer">opendota.api</a></p>
          <p>* No data for stat 'lotuses grabbed' since it was unable to find this info</p>
          <p>* Data for 'watchers taken' is not 100% accurate</p>
          <p>* No data for subtitle 'the Cruel(+13% if a player is killed while in their own fountain)' since death location isn't tracked</p>
        </div>
        <section className='w-full flex flex-col gap-4 items-center py-8'>
          <h2 className='text-white font-bold text-5xl'>Best Stat Scores</h2>
          <h3 className='text-white text-center'>Highest score for each stat, grouped by team and position &mdash; no title/subtitle bonus applied. Click a column to sort.</h3>
          <div className='flex gap-6 text-white'>
            {['core', 'mid', 'support'].map(pos => (
              <label key={pos} className='flex items-center gap-2 capitalize cursor-pointer'>
                <input
                  type='checkbox'
                  checked={visiblePositions[pos]}
                  onChange={() => setVisiblePositions(prev => ({ ...prev, [pos]: !prev[pos] }))}
                />
                {pos}
              </label>
            ))}
          </div>
          <div className='w-full overflow-x-auto'>
            <table className='w-full text-white text-sm'>
              <thead>
                <tr>
                  <th className='text-left px-2 py-2'>Team / position</th>
                  {STAT_SCORE_COLUMNS.map(stat => (
                    <th
                      key={stat}
                      className='text-left px-2 py-2 cursor-pointer hover:text-yellow-500 whitespace-nowrap'
                      onClick={() => setStatSortKey(stat)}
                    >
                      {stat.replace('_', ' ')}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {bestStatScoreRows
                  .filter(row => visiblePositions[row.position])
                  .slice()
                  .sort((a, b) => {
                    if (!statSortKey) return 0;
                    const av = a[statSortKey] === '' ? -Infinity : Number(a[statSortKey]);
                    const bv = b[statSortKey] === '' ? -Infinity : Number(b[statSortKey]);
                    return bv - av;
                  })
                  .map((row, idx) => {
                    const firstPlayerName = row.players.split(' & ')[0];
                    const logo = data[firstPlayerName]?.general?.team_logo;
                    return (
                      <tr key={`${row.seriesID}-${row.teamID}-${row.position}`} className={idx % 2 === 0 ? 'bg-white bg-opacity-5' : ''}>
                        <td className='px-2 py-2 whitespace-nowrap'>
                          {logo && <img src={logo} alt="" className='h-5 inline-block mr-2 align-middle' />}
                          <b>{row.teamName}</b>
                          <span className='ml-2 capitalize text-gray-400'>({row.position})</span>
                          <span className='ml-2 text-gray-400'>— {row.players}</span>
                        </td>
                        {STAT_SCORE_COLUMNS.map(stat => (
                          <td key={stat} className={`px-2 py-2 whitespace-nowrap ${statSortKey === stat ? 'bg-purple-900 bg-opacity-40' : ''}`}>
                            {toFiniteNumber(row[stat]) === 0 ? '-' : toFiniteNumber(row[stat]).toFixed(2)}
                          </td>
                        ))}
                      </tr>
                    );
                  })}
              </tbody>
            </table>
          </div>
        </section>
        <section className='relative flex flex-col items-center w-full gap-4 text-white py-8 mb-12'>
          <div className='flex justify-between w-full'>
            <h2
            className='w-full text-center font-bold text-5xl cursor-pointer'
            onClick={() => setSelectedRole(0)}>
              Core
            </h2>
            <h2 
            className='w-full text-center font-bold text-5xl cursor-pointer'
            onClick={() => setSelectedRole(1)}>
              Mid
            </h2>
            <h2 
            className='w-full text-center font-bold text-5xl cursor-pointer'
            onClick={() => setSelectedRole(2)}>
              Support
            </h2>
          </div>
          <div className='absolute left-0 bottom-0 h-1 w-[33.33%] bg-white transition duration-300'
          style={{ transform: `translateX(${selectedRole * 100}%)` }}></div>
        </section>
        <section className='flex flex-col w-full items-center justify-center py-8'>
          <h4 className='text-white text-lg'>Sort by:</h4>
          <Select name="sort" aria-label="Sort"
          className='p-1 rounded-sm'
          value={sortBy || ''}
          onChange={(e) => setSortBy(e.target.value)}>
            <option value="">None</option>
            {Object.keys(data.Xm[19719].stats).map(color =>
              Object.keys(data.Xm[19719].stats[color]).map(stat => (
                <option key={`${color}-${stat}`} value={stat || ''}>
                  {stat.replace('_', ' ')}
                </option>
              ))
            )}
          </Select>
        </section>
        <section className='grid grid-cols-4 gap-6'>
          {filteredAndSorted.map(([playerName, info]) => (
            <div key={playerName} className='flex flex-col gap-4 w-full bg-gradient-to-b from-purple-950 to-transparent p-4 rounded-lg text-white'>
              <div className='relative'>
                <h3 className='font-semibold text-4xl'>{playerName}</h3>
                <img src={info.general.team_logo} alt="" className='h-10 absolute right-0 top-0 object-contain' />
              </div>
              <h5><b>Total matches:</b>  {Object.entries(info)
                .filter(([leagueId, leagueData]) => 
                  selectedTournaments.includes(leagueId) && leagueData.stats?.green?.roshan_kills
                )
                .reduce((sum, [_, leagueData]) => sum + leagueData.stats.green.roshan_kills.length, 0)}
              </h5>
              {(info.general.pos === 0 || info.general.pos === 1) && <RedStats info={info} />}
              {(info.general.pos === 1 || info.general.pos === 2) && <BlueStats info={info} />}
              <GreenStats info={info} />
              <div>
                <h6><b>Titles:</b></h6>
                {(() => {
                  const aggregatedTitles = {};

                  const titleLabels = {
                    crimson: 'Crimson heroes played',
                    cerulean: 'Cerulean heroes played',
                    emerald: 'Emerald heroes played',
                    royal: 'Royal heroes played',
                    golden: 'Golden heroes played',
                    elemental: 'Elemental heroes played',
                    otherworld: 'Otherworldly heroes played',
                    heroic: 'Heroic heroes played',
                  };

                  Object.entries(info)
                    .filter(([leagueId, leagueData]) => selectedTournaments.includes(leagueId))
                    .forEach(([_, leagueData]) => {
                      if (!leagueData.titles) return;
                      Object.entries(leagueData.titles).forEach(([key, value]) => {
                        aggregatedTitles[key] = (aggregatedTitles[key] || 0) + value;
                      });
                    });

                  return Object.entries(aggregatedTitles).map(([key, value]) => (
                    <div key={key}>
                      {titleLabels[key] || key}: {value}
                    </div>
                  ));
                })()}
              </div>
              <div>
                <h6><b>Subtitles:</b></h6>
                {(() => {
                  const aggregatedSubtitles = {};

                  const subtitleLabels = {
                    'lost_games': 'Underdog (lost games)',
                    'clutch': 'Clutch (last game of a series)',
                    'lucky': "Lucky (match time ends with an 8)"
                  };

                  Object.entries(info)
                    .filter(([leagueId, leagueData]) => selectedTournaments.includes(leagueId))
                    .forEach(([_, leagueData]) => {
                      if (!leagueData.subtitles) return;
                      Object.entries(leagueData.subtitles).forEach(([key, value]) => {
                        aggregatedSubtitles[key] = (aggregatedSubtitles[key] || 0) + value;
                      });
                    });

                  return Object.entries(aggregatedSubtitles).map(([key, value]) => (
                    <div key={key}>
                      {subtitleLabels[key]}: {value}
                    </div>
                  ));
                })()}
              </div>
            </div>
          ))}
        </section>
      </div>
    </>
  )
}

export default App
